# Generated by Django 5.2.8 on 2026-03-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
