# Generated by Django 5.2.8 on 2025-12-11 16:45

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='profile_pics/'),
        ),
    ]
