# Generated by Django 5.2.8 on 2026-01-07 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('group_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('files', 'Files'), ('prompt', 'Prompt'), ('mail', 'Mail'), ('tasks', 'Tasks')], max_length=20)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('execute', 'Execute')], max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perms', to='rbac.role')),
            ],
            options={
                'unique_together': {('role', 'feature', 'action')},
            },
        ),
    ]
