# Generated by Django 5.2.8 on 2026-04-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_seed_owner_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='feature',
            field=models.CharField(choices=[('files', 'Files'), ('prompt', 'Prompt'), ('mail', 'Mail'), ('bulk_mail', 'Bulk Mail'), ('tasks', 'Tasks'), ('calendar', 'Calendar'), ('permission', 'Permission')], max_length=20),
        ),
    ]
