# Generated by Django 5.2.8 on 2025-12-11 16:45

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
