# Generated by Django 5.2.8 on 2025-12-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0002_alter_document_file_alter_document_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='follow_group',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
